### ISSUE TITLE
Plots created

### ISSUE THREAD

**Issue by freshbeka** [freshbeka/Assignment-5#1]
The "figures" folder contains my R script for creating and saving two plots as jpgs. In all, I cleaned the data (removed one outlier), plotted several x-y relationships, then focused on on the relationship between mesh size and the length of fish capture.

I save an exploratory plot then expanded on the idea. In order to group by cite, I converted mesh size into a factor, allowing for visualization of any interactions between mesh size, capture site, and fish length.

**Comment by mdscheuerell** [comment]
Hi Beka. These plots look great, but your `.R` script for generating them wouldn't work for anyone else who might want to run your code. That is, I was hoping to see a `/data` folder as described in Task 1 [here](https://fish497.github.io/website/homework/week_05/hw_05_visualization.html), with a call to `read.csv()` or `readr::read_csv()`.

**Comment by freshbeka** [comment]
Got it. Thank you Mark. I was uncertain. I never saw a csv file, rather I saw that by first calling, "library(FSAdata)" the call "SiscowetMI2004" automatically loaded the relevant data from the FSAdata library. Was the expectation that I took that dataset, converted it to csv, then stored it in a data folder or was there a csv file supplied that I completely missed?

**Comment by mdscheuerell** [comment]
Well, it turns out that the course instructor forgot to include the link to the data file `siscowet.csv` on the assignments page, but that has just been rectified... I'm curious as to why no one else brought that to my attention.

Therefore, it would seem you did the best you could have given the information at hand. Well done!

**Comment by freshbeka** [comment]
Thanks for the clarification, Mark. I suspect no one mentioned it because we hold you in such high regard! Despite your repeated efforts to assure us you are a mere mortal like the rest of us, we just can't accept it! It didn't occur to me there might be information missing, rather I assumed I missed something. Keep up the outstanding work. You are doing an amazing job teaching!

**Comment by mdscheuerell** [comment]
Thanks, Beka. That's really nice to hear.
